package com.leuville.fournisseurservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2016-06-01T11:12:30.905+01:00
 * Generated source version: 3.0.2
 * 
 */
@WebServiceClient(name = "fournisseurService", 
                  wsdlLocation = "https://localhost:8443/tp6/services/fournisseurService?wsdl",
                  targetNamespace = "http://www.leuville.com/fournisseurService/") 
public class FournisseurService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.leuville.com/fournisseurService/", "fournisseurService");
    public final static QName FournisseurServiceSOAP = new QName("http://www.leuville.com/fournisseurService/", "fournisseurServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("https://localhost:8443/tp6/services/fournisseurService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FournisseurService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "https://localhost:8443/tp6/services/fournisseurService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FournisseurService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FournisseurService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FournisseurService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FournisseurService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FournisseurService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FournisseurService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns FournisseurService
     */
    @WebEndpoint(name = "fournisseurServiceSOAP")
    public FournisseurService getFournisseurServiceSOAP() {
        return super.getPort(FournisseurServiceSOAP, FournisseurService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FournisseurService
     */
    @WebEndpoint(name = "fournisseurServiceSOAP")
    public FournisseurService getFournisseurServiceSOAP(WebServiceFeature... features) {
        return super.getPort(FournisseurServiceSOAP, FournisseurService.class, features);
    }

}
