package com.leuville.fournisseurservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2016-06-01T11:12:30.874+01:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://www.leuville.com/fournisseurService/", name = "fournisseurService")
@XmlSeeAlso({ObjectFactory.class})
public interface FournisseurService {

    @WebMethod(action = "http://www.leuville.com/fournisseurService/getPrix")
    @RequestWrapper(localName = "getPrix", targetNamespace = "http://www.leuville.com/fournisseurService/", className = "com.leuville.fournisseurservice.GetPrix")
    @ResponseWrapper(localName = "getPrixResponse", targetNamespace = "http://www.leuville.com/fournisseurService/", className = "com.leuville.fournisseurservice.GetPrixResponse")
    @WebResult(name = "prix", targetNamespace = "http://www.leuville.com/fournisseurService/")
    public float getPrix(
        @WebParam(name = "code-produit", targetNamespace = "http://www.leuville.com/fournisseurService/")
        java.lang.String codeProduit
    );

    @WebMethod(action = "http://www.leuville.com/fournisseurService/commander")
    @RequestWrapper(localName = "commander", targetNamespace = "http://www.leuville.com/fournisseurService/", className = "com.leuville.fournisseurservice.Commander")
    @ResponseWrapper(localName = "commanderResponse", targetNamespace = "http://www.leuville.com/fournisseurService/", className = "com.leuville.fournisseurservice.CommanderResponse")
    @WebResult(name = "commanderResult", targetNamespace = "http://www.leuville.com/fournisseurService/")
    public boolean commander(
        @WebParam(name = "commande", targetNamespace = "http://www.leuville.com/fournisseurService/")
        com.leuville.fournisseurservice.Commander.Commande commande
    );
}
