
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.leuville.fournisseurservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2016-06-01T10:30:17.167+01:00
 * Generated source version: 3.0.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "fournisseurService",
                      portName = "fournisseurServiceSOAP",
                      targetNamespace = "http://www.leuville.com/fournisseurService/",
                      wsdlLocation = "web/WEB-INF/wsdl/fournisseurService.wsdl",
                      endpointInterface = "com.leuville.fournisseurservice.FournisseurService")
                      
public class fournisseurServiceSOAPImpl implements FournisseurService {

    private static final Logger LOG = Logger.getLogger(fournisseurServiceSOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see com.leuville.fournisseurservice.FournisseurService#getPrix(java.lang.String  codeProduit )*
     */
    public float getPrix(java.lang.String codeProduit) { 
        LOG.info("Executing operation getPrix");
        System.out.println(codeProduit);
        try {
            float _return = 1000.0f;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.leuville.fournisseurservice.FournisseurService#commander(com.leuville.fournisseurservice.Commander.Commande  commande )*
     */
    public boolean commander(com.leuville.fournisseurservice.Commander.Commande commande) { 
        LOG.info("Executing operation commander");
        System.out.println(commande);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
